server:
  port: 8080

service:
  monitor:
    token:
      scheme: https
      host: hawkeye-test.icekredit.com # ${HOST_ADDRESS:}
      path: /api/login.do
      username: liyang
      password: b21f212017bb5bc0aadb6d6fecb29ff2
    path:
      collection: D:\postman\postman_collection2.json # ${COLLECTION_JSON_PATH:}
      global: D:\postman\postman_globals.json # ${GLOBAL_JSON_PATH:}
      environment: D:\postman\postman_environment.json # ${ENV_JSON_PATH:}

